use unwrap_or_else, not expect, per clippy
+cargo clippy --all -- -D warnings
   Compiling rethnet_evm_napi v0.1.0-dev (/home/gene/dev/nomiclabs/rethnet/crates/rethnet_evm_napi)
    Checking rethnet v0.1.0-dev (/home/gene/dev/nomiclabs/rethnet/crates/rethnet)
    Checking rpc_client v0.1.0 (/home/gene/dev/nomiclabs/rethnet/crates/rpc_client)
error: use of `expect` followed by a function call
  --> crates/rpc_client/src/lib.rs:40:92
   |
40 |       let success: jsonrpc_types::Success<Transaction> = serde_json::from_str(response_text).expect(
   |  ____________________________________________________________________________________________^
41 | |         format!(
42 | |             "failed to interpret as Transaction response string \"{}\"",
43 | |             response_text
44 | |         )
45 | |         .as_str(),
46 | |     );
   | |_____^
   |
   = note: `-D clippy::expect-fun-call` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call
help: try this
   |
40 ~     let success: jsonrpc_types::Success<Transaction> = serde_json::from_str(response_text).unwrap_or_else(|_| panic!("failed to interpret as Transaction response string \"{}\"",
41 ~             response_text));
   |

error: could not compile `rpc_client` due to previous error